name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA2RBAZ4SIGDKVGAHC
          aws-secret-access-key: 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
          aws-region: us-west-1
